[features]
seeds = false
skip-lint = false
[programs.localnet]
noter = "8HhR4ik3Mwo69aQ3VqXXT4vasGUPXxyew4PEHjXw1rGu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/tommylee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
